### PR TITLE
add centralnovel source [need observation]

### PR DESCRIPTION
**Pull request by gabriel-batistuta**
#1370 issue

Hi, I managed to do a good part of the Central Novel plugin but I think it needs a more complete review by a more experienced person on the subject, so whoever is available to help me with this plugin I would appreciate it.

### CODE REVIEW

**Comment by nyagami** [comment]
This source was detected as a Lightnovelwp multisrc theme. 
If you dont know how to add a multisrc, you can take this [video](https://youtu.be/1DP3p6sB_VE?si=ayUk_8vnOuWvNYAJ) as a reference.

**Comment by gabriel-batistuta** [comment]
It seems that the source already exists in multisrc, so I deleted the one I made in the Portuguese folder and the icon. I also tested the existing centralnovel plugin in multisrc and it seems to be broken, none of the options work (Popular Novels, Search Novels, Parse Novel, Parse Chapter)

**Comment by error7404** [comment]
I just tried it and it works fine, is it working in WebView for you?
Maybe try to use a vpn

**Comment by gabriel-batistuta** [comment]
the complete log:
```shell
/home/gabriel/Documentos/programming/lnreader-plugins/node_modules/http-proxy/lib/http-proxy/index.js:120
    throw err;
    ^

AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1128:18)
    at internalConnectMultiple (node:net:1196:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1720:5)
    at listOnTimeout (node:internal/timers:616:11)
    at process.processTimers (node:internal/timers:549:7) {
  code: 'ETIMEDOUT',
  [errors]: [
    Error: connect ETIMEDOUT 62.72.33.38:443
        at createConnectionError (node:net:1656:14)
        at Timeout.internalConnectMultipleTimeout (node:net:1715:38)
        at listOnTimeout (node:internal/timers:616:11)
        at process.processTimers (node:internal/timers:549:7) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '62.72.33.38',
      port: 443
    },
    Error: connect ENETUNREACH 2a02:4780:c:a441::1:443 - Local (:::0)
        at internalConnectMultiple (node:net:1192:16)
        at Timeout.internalConnectMultipleTimeout (node:net:1720:5)
        at listOnTimeout (node:internal/timers:616:11)
        at process.processTimers (node:internal/timers:549:7) {
      errno: -101,
      code: 'ENETUNREACH',
      syscall: 'connect',
      address: '2a02:4780:c:a441::1',
      port: 443
    }
  ]
}

Node.js v23.1.0
```

**Comment by error7404** [comment]
I meant in the app

**Comment by gabriel-batistuta** [comment]
I can't find the multisrc sources in the app, it also applies to centralnovel, where can I find them?

**Comment by error7404** [comment]
are you on the latest beta?

**Comment by gabriel-batistuta** [comment]
I wasn't before, I updated now

**Comment by gabriel-batistuta** [comment]
but I need a url repository for centralnovel?

**Comment by gabriel-batistuta** [comment]
all right, everything is ok, this issue can be closed, thanks for help

**Pull request closed without merging**
