### PR TITLE
new source dilar.tube

### PR DESCRIPTION
**Pull request by Dredd1987**
I got stuck on search and chapter parsing. Maybe you can help.

### CODE REVIEW

**Comment by hoangquan0511** [comment]
Where did you get stuck?. Like cloudflare issue or understanding language issue

**Comment by Dredd1987** [comment]
I fail to fetch the response of search, the entire novels novelsearch function doesn't work, as for the chapterText I think it pulls the page before the text being populated. And the search response is encrypted I think a got It right but don't know if can be done in the plugin it self or it gonna severely affect the preformance

**Comment by Dredd1987** [comment]
It's a bit difficult to sort through the site am translating as I go

**Comment by hoangquan0511** [comment]
I see that they use quick_search api entry for searching in app bar. Have you tired it?

**Comment by K1ngfish3r** [comment]
image
```ts
const formData = new FormData();
formData.append('query', 'wife');
formData.append('includes', '["Manga","Team","Member"]');
fetch('https://dilar.tube/api/quick_search', {
    method: 'POST',
    body: formData,
}).then(a => a.json()).then(b => console.log(b));
```
edit as needed

**Comment by K1ngfish3r** [comment]
What's current status?

**Comment by Rider21** [comment]
By default, the `crypto` module is missing from `react-native`.
Have you found a replacement for it?
For example, `expo-crypto`, `react-native-quick-crypto`, `crypto-browserify`.

**Comment by Dredd1987** [comment]
> What's current status?

Sorry, I got really busy. The chapter content is still returning an error with the connection being refused.

**Comment by Dredd1987** [comment]
> By default, the `crypto` module is missing from `react-native`. Have you found a replacement for it? For example, ~`expo-crypto`~, `react-native-quick-crypto`, `crypto-browserify`.

I abandoned this approach because of a CORS error. It works in my tests, but not at all in the app.

**Review by rajarsheechatterjee — APPROVED** [review]

**Pull request merged**
