### PR TITLE
RainofSnow: Add filters and Fix dates

### PR DESCRIPTION
**Pull request by K1ngfish3r**
Adds basic filters.
Fixes invalid date issue, closes https://github.com/LNReader/lnreader-plugins/issues/1154

### CODE REVIEW

**Comment by nyagami** [comment]
Still no chapter

**Comment by K1ngfish3r** [comment]
Pressing the 1 doesn't work?

**Comment by nyagami** [comment]
Oh i forgor this is pagedplugin xD

**Review by nyagami — APPROVED** [review]

**Comment by K1ngfish3r** [comment]
image
I moved logic for page 1

**Pull request merged**
