### PR TITLE
Update sources.json

### PR DESCRIPTION
**Pull request by Abdalrhman1235**
The new url of kolnovel

### CODE REVIEW

**Comment by nyagami** [comment]
you should add versionIncrements to make it updatable from app

**Comment by Abdalrhman1235** [comment]
How should I do that

**Comment by nyagami** [comment]
like this
```json
  {
    "id": "arnovel",
    "sourceSite": "https://ar-novel.com/",
    "sourceName": "ArNovel",
    "options": {
      "useNewChapterEndpoint": true,
      "lang": "Arabic",
      "versionIncrements": 1
    }
  },
```

**Comment by Abdalrhman1235** [comment]
When I do this reverse chapters becomes messed up

**Comment by Abdalrhman1235** [comment]
Nvrm done

**Comment by nyagami** [comment]
Why did you create a new PR?

**Comment by Abdalrhman1235** [comment]
Because I couldn't make it in the same one

**Comment by nyagami** [comment]
done in https://github.com/LNReader/lnreader-plugins/pull/1019

**Pull request closed without merging**
